"""跨模块数据契约：LLM 解析结构、服务 IO。磁盘格式见 docs/persist-formats.md。"""

from core.schemas.llm import (
    BulkStatePayload,
    BulkSummariesPayload,
    MaintainPayload,
    ObserveBlock,
    ObserveItem,
    QualityPayload,
    RemediateChangeLogPayload,
    RemediateDiagnosePayload,
    count_report_issues,
    normalize_maintain_payload,
    normalize_quality_payload,
    parse_bulk_state,
    parse_bulk_summaries,
    parse_observe_proposals,
    parse_post_chapter_maintain,
    parse_quality_bundle,
    parse_remediate_bulk_change_log,
    parse_remediate_change_log,
    parse_remediate_diagnose,
)
from core.schemas.service import (
    BookSnapshot,
    ChapterRef,
    ChapterWork,
    PersistOutcome,
    ServiceResult,
)

__all__ = [
    "BookSnapshot",
    "BulkStatePayload",
    "BulkSummariesPayload",
    "ChapterRef",
    "ChapterWork",
    "MaintainPayload",
    "ObserveBlock",
    "ObserveItem",
    "PersistOutcome",
    "QualityPayload",
    "RemediateChangeLogPayload",
    "RemediateDiagnosePayload",
    "ServiceResult",
    "count_report_issues",
    "normalize_maintain_payload",
    "normalize_quality_payload",
    "parse_bulk_state",
    "parse_bulk_summaries",
    "parse_observe_proposals",
    "parse_post_chapter_maintain",
    "parse_quality_bundle",
    "parse_remediate_bulk_change_log",
    "parse_remediate_change_log",
    "parse_remediate_diagnose",
]
